try using phoenix-actions/test-reporting (#1595)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -55,7 +55,18 @@ jobs:
           run: dotnet build SentryNoSamples.slnf -c Release /p:CopyLocalLockFileAssemblies=true
 
         - name: Test
-          run: dotnet test SentryNoSamples.slnf -c Release --no-build -l "GitHubActions;report-warnings=false"
+          run: dotnet test SentryNoSamples.slnf -c Release --no-build -l "GitHubActions;report-warnings=false" -l "trx;LogFileName=${{ matrix.os }}-test-results.trx"
+
+        - name: Create Test Report
+          uses: phoenix-actions/test-reporting@4b942144e31c4039ac808d9b29945864b628a574
+          # run this step even if previous step failed
+          if: success() || failure()
+          with:
+            name: Unit Test Results (${{ matrix.os }})
+            path: '**/*.trx'
+            reporter: dotnet-trx
+            list-suites: 'all'
+            list-tests: 'failed'
 
         - name: Pack
           # only pack on windows since we need classic .net assemblies
